"""
Copyright 2017 Ryan Wick (rrwick@gmail.com)
https://github.com/rrwick/Porechop

This module contains the class and sequences for known adapters used in Oxford Nanopore library
preparation kits.

This file is part of Porechop. Porechop is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version. Porechop is distributed in
the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details. You should have received a copy of the GNU General Public License along with Porechop. If
not, see <http://www.gnu.org/licenses/>.
"""


class Adapter(object):

    def __init__(self, name, start_sequence=None, end_sequence=None, both_ends_sequence=None):
        self.name = name
        self.start_sequence = start_sequence if start_sequence else []
        self.end_sequence = end_sequence if end_sequence else []
        if both_ends_sequence:
            self.start_sequence = both_ends_sequence
            self.end_sequence = both_ends_sequence
        self.best_start_score, self.best_end_score = 0.0, 0.0

    def best_start_or_end_score(self):
        return max(self.best_start_score, self.best_end_score)

    def is_barcode(self):
        return 'barcod' in self.name  # will catch 'barcode' and 'barcoding'

    def get_barcode_name(self):
        """
        Gets the barcode name for the output files. We want a concise name, so it looks at all
        options and chooses the shortest.
        """
        possible_names = [self.name, self.start_sequence[0], self.end_sequence[0]]
        barcode_name = sorted(possible_names, key=lambda x: len(x))[0]
        return barcode_name.replace(' ', '_')


ADAPTERS = [Adapter('SQK-MAP006',
                    start_sequence=('SQK-MAP006_Y_Top_SK63',    'GGTTGTTTCTGTTGGTGCTGATATTGCT'),
                    end_sequence=  ('SQK-MAP006_Y_Bottom_SK64', 'GCAATATCAGCACCAACAGAAA')),
            Adapter('SQK-MAP006 Short',
                    start_sequence=('SQK-MAP006_Short_Y_Top_LI32',    'CGGCGTCTGCTTGGGTGTTTAACCT'),
                    end_sequence=  ('SQK-MAP006_Short_Y_Bottom_LI33', 'GGTTAAACACCCAAGCAGACGCCG')),

            Adapter('SQK-NSK007',
                    start_sequence=('SQK-NSK007_Y_Top',    'AATGTACTTCGTTCAGTTACGTATTGCT'),
                    end_sequence=  ('SQK-NSK007_Y_Bottom', 'GCAATACGTAACTGAACGAAGT')),

            Adapter('Native barcoding 1',
                    start_sequence=('NB01_rev', 'AGGTTAACACAAAGACACCGACAACTTTCTTCAGCACC'),
                    end_sequence=  ('NB01',     'GGTGCTGAAGAAAGTTGTCGGTGTCTTTGTGTTAACCT')),
            Adapter('Native barcoding 2',
                    start_sequence=('NB02_rev', 'AGGTTAAACAGACGACTACAAACGGAATCGACAGCACC'),
                    end_sequence=  ('NB02',     'GGTGCTGTCGATTCCGTTTGTAGTCGTCTGTTTAACCT')),
            Adapter('Native barcoding 3',
                    start_sequence=('NB03_rev', 'AGGTTAACCTGGTAACTGGGACACAAGACTCCAGCACC'),
                    end_sequence=  ('NB03',     'GGTGCTGGAGTCTTGTGTCCCAGTTACCAGGTTAACCT')),
            Adapter('Native barcoding 4',
                    start_sequence=('NB04_rev', 'AGGTTAATAGGGAAACACGATAGAATCCGAACAGCACC'),
                    end_sequence=  ('NB04',     'GGTGCTGTTCGGATTCTATCGTGTTTCCCTATTAACCT')),
            Adapter('Native barcoding 5',
                    start_sequence=('NB05_rev', 'AGGTTAAAAGGTTACACAAACCCTGGACAAGCAGCACC'),
                    end_sequence=  ('NB05',     'GGTGCTGCTTGTCCAGGGTTTGTGTAACCTTTTAACCT')),
            Adapter('Native barcoding 6',
                    start_sequence=('NB06_rev', 'AGGTTAAGACTACTTTCTGCCTTTGCGAGAACAGCACC'),
                    end_sequence=  ('NB06',     'GGTGCTGTTCTCGCAAAGGCAGAAAGTAGTCTTAACCT')),
            Adapter('Native barcoding 7',
                    start_sequence=('NB07_rev', 'AGGTTAAAAGGATTCATTCCCACGGTAACACCAGCACC'),
                    end_sequence=  ('NB07',     'GGTGCTGGTGTTACCGTGGGAATGAATCCTTTTAACCT')),
            Adapter('Native barcoding 8',
                    start_sequence=('NB08_rev', 'AGGTTAAACGTAACTTGGTTTGTTCCCTGAACAGCACC'),
                    end_sequence=  ('NB08',     'GGTGCTGTTCAGGGAACAAACCAAGTTACGTTTAACCT')),
            Adapter('Native barcoding 9',
                    start_sequence=('NB09_rev', 'AGGTTAAAACCAAGACTCGCTGTGCCTAGTTCAGCACC'),
                    end_sequence=  ('NB09',     'GGTGCTGAACTAGGCACAGCGAGTCTTGGTTTTAACCT')),
            Adapter('Native barcoding 10',
                    start_sequence=('NB10_rev', 'AGGTTAAGAGAGGACAAAGGTTTCAACGCTTCAGCACC'),
                    end_sequence=  ('NB10',     'GGTGCTGAAGCGTTGAAACCTTTGTCCTCTCTTAACCT')),
            Adapter('Native barcoding 11',
                    start_sequence=('NB11_rev', 'AGGTTAATCCATTCCCTCCGATAGATGAAACCAGCACC'),
                    end_sequence=  ('NB11',     'GGTGCTGGTTTCATCTATCGGAGGGAATGGATTAACCT')),
            Adapter('Native barcoding 12',
                    start_sequence=('NB12_rev', 'AGGTTAATCCGATTCTGCTTCTTTCTACCTGCAGCACC'),
                    end_sequence=  ('NB12',     'GGTGCTGCAGGTAGAAAGAAGCAGAATCGGATTAACCT')),

            Adapter('PCR barcoding 1',
                    start_sequence=('BC01_rev', 'AAGAAAGTTGTCGGTGTCTTTGTG'),
                    end_sequence=  ('BC01',     'CACAAAGACACCGACAACTTTCTT')),
            Adapter('PCR barcoding 2',
                    start_sequence=('BC02_rev', 'TCGATTCCGTTTGTAGTCGTCTGT'),
                    end_sequence=  ('BC02',     'ACAGACGACTACAAACGGAATCGA')),
            Adapter('PCR barcoding 3',
                    start_sequence=('BC03_rev', 'GAGTCTTGTGTCCCAGTTACCAGG'),
                    end_sequence=  ('BC03',     'CCTGGTAACTGGGACACAAGACTC')),
            Adapter('PCR barcoding 4',
                    start_sequence=('BC04_rev', 'TTCGGATTCTATCGTGTTTCCCTA'),
                    end_sequence=  ('BC04',     'TAGGGAAACACGATAGAATCCGAA')),
            Adapter('PCR barcoding 5',
                    start_sequence=('BC05_rev', 'CTTGTCCAGGGTTTGTGTAACCTT'),
                    end_sequence=  ('BC05',     'AAGGTTACACAAACCCTGGACAAG')),
            Adapter('PCR barcoding 6',
                    start_sequence=('BC06_rev', 'TTCTCGCAAAGGCAGAAAGTAGTC'),
                    end_sequence=  ('BC06',     'GACTACTTTCTGCCTTTGCGAGAA')),
            Adapter('PCR barcoding 7',
                    start_sequence=('BC07_rev', 'GTGTTACCGTGGGAATGAATCCTT'),
                    end_sequence=  ('BC07',     'AAGGATTCATTCCCACGGTAACAC')),
            Adapter('PCR barcoding 8',
                    start_sequence=('BC08_rev', 'TTCAGGGAACAAACCAAGTTACGT'),
                    end_sequence=  ('BC08',     'ACGTAACTTGGTTTGTTCCCTGAA')),
            Adapter('PCR barcoding 9',
                    start_sequence=('BC09_rev', 'AACTAGGCACAGCGAGTCTTGGTT'),
                    end_sequence=  ('BC09',     'AACCAAGACTCGCTGTGCCTAGTT')),
            Adapter('PCR barcoding 10',
                    start_sequence=('BC10_rev', 'AAGCGTTGAAACCTTTGTCCTCTC'),
                    end_sequence=  ('BC10',     'GAGAGGACAAAGGTTTCAACGCTT')),
            Adapter('PCR barcoding 11',
                    start_sequence=('BC11_rev', 'GTTTCATCTATCGGAGGGAATGGA'),
                    end_sequence=  ('BC11',     'TCCATTCCCTCCGATAGATGAAAC')),
            Adapter('PCR barcoding 12',
                    start_sequence=('BC12_rev', 'CAGGTAGAAAGAAGCAGAATCGGA'),
                    end_sequence=  ('BC12',     'TCCGATTCTGCTTCTTTCTACCTG')),
            Adapter('PCR barcoding 13',
                    start_sequence=('BC13_rev', 'AGAACGACTTCCATACTCGTGTGA'),
                    end_sequence=  ('BC13',     'TCACACGAGTATGGAAGTCGTTCT')),
            Adapter('PCR barcoding 14',
                    start_sequence=('BC14_rev', 'AACGAGTCTCTTGGGACCCATAGA'),
                    end_sequence=  ('BC14',     'TCTATGGGTCCCAAGAGACTCGTT')),
            Adapter('PCR barcoding 15',
                    start_sequence=('BC15_rev', 'AGGTCTACCTCGCTAACACCACTG'),
                    end_sequence=  ('BC15',     'CAGTGGTGTTAGCGAGGTAGACCT')),
            Adapter('PCR barcoding 16',
                    start_sequence=('BC16_rev', 'CGTCAACTGACAGTGGTTCGTACT'),
                    end_sequence=  ('BC16',     'AGTACGAACCACTGTCAGTTGACG')),
            Adapter('PCR barcoding 17',
                    start_sequence=('BC17_rev', 'ACCCTCCAGGAAAGTACCTCTGAT'),
                    end_sequence=  ('BC17',     'ATCAGAGGTACTTTCCTGGAGGGT')),
            Adapter('PCR barcoding 18',
                    start_sequence=('BC18_rev', 'CCAAACCCAACAACCTAGATAGGC'),
                    end_sequence=  ('BC18',     'GCCTATCTAGGTTGTTGGGTTTGG')),
            Adapter('PCR barcoding 19',
                    start_sequence=('BC19_rev', 'GTTCCTCGTGCAGTGTCAAGAGAT'),
                    end_sequence=  ('BC19',     'ATCTCTTGACACTGCACGAGGAAC')),
            Adapter('PCR barcoding 20',
                    start_sequence=('BC20_rev', 'TTGCGTCCTGTTACGAGAACTCAT'),
                    end_sequence=  ('BC20',     'ATGAGTTCTCGTAACAGGACGCAA')),
            Adapter('PCR barcoding 21',
                    start_sequence=('BC21_rev', 'GAGCCTCTCATTGTCCGTTCTCTA'),
                    end_sequence=  ('BC21',     'TAGAGAACGGACAATGAGAGGCTC')),
            Adapter('PCR barcoding 22',
                    start_sequence=('BC22_rev', 'ACCACTGCCATGTATCAAAGTACG'),
                    end_sequence=  ('BC22',     'CGTACTTTGATACATGGCAGTGGT')),
            Adapter('PCR barcoding 23',
                    start_sequence=('BC23_rev', 'CTTACTACCCAGTGAACCTCCTCG'),
                    end_sequence=  ('BC23',     'CGAGGAGGTTCACTGGGTAGTAAG')),
            Adapter('PCR barcoding 24',
                    start_sequence=('BC24_rev', 'GCATAGTTCTGCATGATGGGTTAG'),
                    end_sequence=  ('BC24',     'CTAACCCATCATGCAGAACTATGC')),
            Adapter('PCR barcoding 25',
                    start_sequence=('BC25_rev', 'GTAAGTTGGGTATGCAACGCAATG'),
                    end_sequence=  ('BC25',     'CATTGCGTTGCATACCCAACTTAC')),
            Adapter('PCR barcoding 26',
                    start_sequence=('BC26_rev', 'CATACAGCGACTACGCATTCTCAT'),
                    end_sequence=  ('BC26',     'ATGAGAATGCGTAGTCGCTGTATG')),
            Adapter('PCR barcoding 27',
                    start_sequence=('BC27_rev', 'CGACGGTTAGATTCACCTCTTACA'),
                    end_sequence=  ('BC27',     'TGTAAGAGGTGAATCTAACCGTCG')),
            Adapter('PCR barcoding 28',
                    start_sequence=('BC28_rev', 'TGAAACCTAAGAAGGCACCGTATC'),
                    end_sequence=  ('BC28',     'GATACGGTGCCTTCTTAGGTTTCA')),
            Adapter('PCR barcoding 29',
                    start_sequence=('BC29_rev', 'CTAGACACCTTGGGTTGACAGACC'),
                    end_sequence=  ('BC29',     'GGTCTGTCAACCCAAGGTGTCTAG')),
            Adapter('PCR barcoding 30',
                    start_sequence=('BC30_rev', 'TCAGTGAGGATCTACTTCGACCCA'),
                    end_sequence=  ('BC30',     'TGGGTCGAAGTAGATCCTCACTGA')),
            Adapter('PCR barcoding 31',
                    start_sequence=('BC31_rev', 'TGCGTACAGCAATCAGTTACATTG'),
                    end_sequence=  ('BC31',     'CAATGTAACTGATTGCTGTACGCA')),
            Adapter('PCR barcoding 32',
                    start_sequence=('BC32_rev', 'CCAGTAGAAGTCCGACAACGTCAT'),
                    end_sequence=  ('BC32',     'ATGACGTTGTCGGACTTCTACTGG')),
            Adapter('PCR barcoding 33',
                    start_sequence=('BC33_rev', 'CAGACTTGGTACGGTTGGGTAACT'),
                    end_sequence=  ('BC33',     'AGTTACCCAACCGTACCAAGTCTG')),
            Adapter('PCR barcoding 34',
                    start_sequence=('BC34_rev', 'GGACGAAGAACTCAAGTCAAAGGC'),
                    end_sequence=  ('BC34',     'GCCTTTGACTTGAGTTCTTCGTCC')),
            Adapter('PCR barcoding 35',
                    start_sequence=('BC35_rev', 'CTACTTACGAAGCTGAGGGACTGC'),
                    end_sequence=  ('BC35',     'GCAGTCCCTCAGCTTCGTAAGTAG')),
            Adapter('PCR barcoding 36',
                    start_sequence=('BC36_rev', 'ATGTCCCAGTTAGAGGAGGAAACA'),
                    end_sequence=  ('BC36',     'TGTTTCCTCCTCTAACTGGGACAT')),
            Adapter('PCR barcoding 37',
                    start_sequence=('BC37_rev', 'GCTTGCGATTGATGCTTAGTATCA'),
                    end_sequence=  ('BC37',     'TGATACTAAGCATCAATCGCAAGC')),
            Adapter('PCR barcoding 38',
                    start_sequence=('BC38_rev', 'ACCACAGGAGGACGATACAGAGAA'),
                    end_sequence=  ('BC38',     'TTCTCTGTATCGTCCTCCTGTGGT')),
            Adapter('PCR barcoding 39',
                    start_sequence=('BC39_rev', 'CCACAGTGTCAACTAGAGCCTCTC'),
                    end_sequence=  ('BC39',     'GAGAGGCTCTAGTTGACACTGTGG')),
            Adapter('PCR barcoding 40',
                    start_sequence=('BC40_rev', 'TAGTTTGGATGACCAAGGATAGCC'),
                    end_sequence=  ('BC40',     'GGCTATCCTTGGTCATCCAAACTA')),
            Adapter('PCR barcoding 41',
                    start_sequence=('BC41_rev', 'GGAGTTCGTCCAGAGAAGTACACG'),
                    end_sequence=  ('BC41',     'CGTGTACTTCTCTGGACGAACTCC')),
            Adapter('PCR barcoding 42',
                    start_sequence=('BC42_rev', 'CTACGTGTAAGGCATACCTGCCAG'),
                    end_sequence=  ('BC42',     'CTGGCAGGTATGCCTTACACGTAG')),
            Adapter('PCR barcoding 43',
                    start_sequence=('BC43_rev', 'CTTTCGTTGTTGACTCGACGGTAG'),
                    end_sequence=  ('BC43',     'CTACCGTCGAGTCAACAACGAAAG')),
            Adapter('PCR barcoding 44',
                    start_sequence=('BC44_rev', 'AGTAGAAAGGGTTCCTTCCCACTC'),
                    end_sequence=  ('BC44',     'GAGTGGGAAGGAACCCTTTCTACT')),
            Adapter('PCR barcoding 45',
                    start_sequence=('BC45_rev', 'GATCCAACAGAGATGCCTTCAGTG'),
                    end_sequence=  ('BC45',     'CACTGAAGGCATCTCTGTTGGATC')),
            Adapter('PCR barcoding 46',
                    start_sequence=('BC46_rev', 'GCTGTGTTCCACTTCATTCTCCTG'),
                    end_sequence=  ('BC46',     'CAGGAGAATGAAGTGGAACACAGC')),
            Adapter('PCR barcoding 47',
                    start_sequence=('BC47_rev', 'GTGCAACTTTCCCACAGGTAGTTC'),
                    end_sequence=  ('BC47',     'GAACTACCTGTGGGAAAGTTGCAC')),
            Adapter('PCR barcoding 48',
                    start_sequence=('BC48_rev', 'CATCTGGAACGTGGTACACCTGTA'),
                    end_sequence=  ('BC48',     'TACAGGTGTACCACGTTCCAGATG')),
            Adapter('PCR barcoding 49',
                    start_sequence=('BC49_rev', 'ACTGGTGCAGCTTTGAACATCTAG'),
                    end_sequence=  ('BC49',     'CTAGATGTTCAAAGCTGCACCAGT')),
            Adapter('PCR barcoding 50',
                    start_sequence=('BC50_rev', 'ATGGACTTTGGTAACTTCCTGCGT'),
                    end_sequence=  ('BC50',     'ACGCAGGAAGTTACCAAAGTCCAT')),
            Adapter('PCR barcoding 51',
                    start_sequence=('BC51_rev', 'GTTGAATGAGCCTACTGGGTCCTC'),
                    end_sequence=  ('BC51',     'GAGGACCCAGTAGGCTCATTCAAC')),
            Adapter('PCR barcoding 52',
                    start_sequence=('BC52_rev', 'TGAGAGACAAGATTGTTCGTGGAC'),
                    end_sequence=  ('BC52',     'GTCCACGAACAATCTTGTCTCTCA')),
            Adapter('PCR barcoding 53',
                    start_sequence=('BC53_rev', 'AGATTCAGACCGTCTCATGCAAAG'),
                    end_sequence=  ('BC53',     'CTTTGCATGAGACGGTCTGAATCT')),
            Adapter('PCR barcoding 54',
                    start_sequence=('BC54_rev', 'CAAGAGCTTTGACTAAGGAGCATG'),
                    end_sequence=  ('BC54',     'CATGCTCCTTAGTCAAAGCTCTTG')),
            Adapter('PCR barcoding 55',
                    start_sequence=('BC55_rev', 'TGGAAGATGAGACCCTGATCTACG'),
                    end_sequence=  ('BC55',     'CGTAGATCAGGGTCTCATCTTCCA')),
            Adapter('PCR barcoding 56',
                    start_sequence=('BC56_rev', 'TCACTACTCAACAGGTGGCATGAA'),
                    end_sequence=  ('BC56',     'TTCATGCCACCTGTTGAGTAGTGA')),
            Adapter('PCR barcoding 57',
                    start_sequence=('BC57_rev', 'GCTAGGTCAATCTCCTTCGGAAGT'),
                    end_sequence=  ('BC57',     'ACTTCCGAAGGAGATTGACCTAGC')),
            Adapter('PCR barcoding 58',
                    start_sequence=('BC58_rev', 'CAGGTTACTCCTCCGTGAGTCTGA'),
                    end_sequence=  ('BC58',     'TCAGACTCACGGAGGAGTAACCTG')),
            Adapter('PCR barcoding 59',
                    start_sequence=('BC59_rev', 'TCAATCAAGAAGGGAAAGCAAGGT'),
                    end_sequence=  ('BC59',     'ACCTTGCTTTCCCTTCTTGATTGA')),
            Adapter('PCR barcoding 60',
                    start_sequence=('BC60_rev', 'CATGTTCAACCAAGGCTTCTATGG'),
                    end_sequence=  ('BC60',     'CCATAGAAGCCTTGGTTGAACATG')),
            Adapter('PCR barcoding 61',
                    start_sequence=('BC61_rev', 'AGAGGGTACTATGTGCCTCAGCAC'),
                    end_sequence=  ('BC61',     'GTGCTGAGGCACATAGTACCCTCT')),
            Adapter('PCR barcoding 62',
                    start_sequence=('BC62_rev', 'CACCCACACTTACTTCAGGACGTA'),
                    end_sequence=  ('BC62',     'TACGTCCTGAAGTAAGTGTGGGTG')),
            Adapter('PCR barcoding 63',
                    start_sequence=('BC63_rev', 'TTCTGAAGTTCCTGGGTCTTGAAC'),
                    end_sequence=  ('BC63',     'GTTCAAGACCCAGGAACTTCAGAA')),
            Adapter('PCR barcoding 64',
                    start_sequence=('BC64_rev', 'GACAGACACCGTTCATCGACTTTC'),
                    end_sequence=  ('BC64',     'GAAAGTCGATGAACGGTGTCTGTC')),
            Adapter('PCR barcoding 65',
                    start_sequence=('BC65_rev', 'TTCTCAGTCTTCCTCCAGACAAGG'),
                    end_sequence=  ('BC65',     'CCTTGTCTGGAGGAAGACTGAGAA')),
            Adapter('PCR barcoding 66',
                    start_sequence=('BC66_rev', 'CCGATCCTTGTGGCTTCTAACTTC'),
                    end_sequence=  ('BC66',     'GAAGTTAGAAGCCACAAGGATCGG')),
            Adapter('PCR barcoding 67',
                    start_sequence=('BC67_rev', 'GTTTGTCATACTCGTGTGCTCACC'),
                    end_sequence=  ('BC67',     'GGTGAGCACACGAGTATGACAAAC')),
            Adapter('PCR barcoding 68',
                    start_sequence=('BC68_rev', 'GAATCTAAGCAAACACGAAGGTGG'),
                    end_sequence=  ('BC68',     'CCACCTTCGTGTTTGCTTAGATTC')),
            Adapter('PCR barcoding 69',
                    start_sequence=('BC69_rev', 'TACAGTCCGAGCCTCATGTGATCT'),
                    end_sequence=  ('BC69',     'AGATCACATGAGGCTCGGACTGTA')),
            Adapter('PCR barcoding 70',
                    start_sequence=('BC70_rev', 'ACCGAGATCCTACGAATGGAGTGT'),
                    end_sequence=  ('BC70',     'ACACTCCATTCGTAGGATCTCGGT')),
            Adapter('PCR barcoding 71',
                    start_sequence=('BC71_rev', 'CCTGGGAGCATCAGGTAGTAACAG'),
                    end_sequence=  ('BC71',     'CTGTTACTACCTGATGCTCCCAGG')),
            Adapter('PCR barcoding 72',
                    start_sequence=('BC72_rev', 'TAGCTGACTGTCTTCCATACCGAC'),
                    end_sequence=  ('BC72',     'GTCGGTATGGAAGACAGTCAGCTA')),
            Adapter('PCR barcoding 73',
                    start_sequence=('BC73_rev', 'AAGAAACAGGATGACAGAACCCTC'),
                    end_sequence=  ('BC73',     'GAGGGTTCTGTCATCCTGTTTCTT')),
            Adapter('PCR barcoding 74',
                    start_sequence=('BC74_rev', 'TACAAGCATCCCAACACTTCCACT'),
                    end_sequence=  ('BC74',     'AGTGGAAGTGTTGGGATGCTTGTA')),
            Adapter('PCR barcoding 75',
                    start_sequence=('BC75_rev', 'GACCATTGTGATGAACCCTGTTGT'),
                    end_sequence=  ('BC75',     'ACAACAGGGTTCATCACAATGGTC')),
            Adapter('PCR barcoding 76',
                    start_sequence=('BC76_rev', 'ATGCTTGTTACATCAACCCTGGAC'),
                    end_sequence=  ('BC76',     'GTCCAGGGTTGATGTAACAAGCAT')),
            Adapter('PCR barcoding 77',
                    start_sequence=('BC77_rev', 'CGACCTGTTTCTCAGGGATACAAC'),
                    end_sequence=  ('BC77',     'GTTGTATCCCTGAGAAACAGGTCG')),
            Adapter('PCR barcoding 78',
                    start_sequence=('BC78_rev', 'AACAACCGAACCTTTGAATCAGAA'),
                    end_sequence=  ('BC78',     'TTCTGATTCAAAGGTTCGGTTGTT')),
            Adapter('PCR barcoding 79',
                    start_sequence=('BC79_rev', 'TCTCGGAGATAGTTCTCACTGCTG'),
                    end_sequence=  ('BC79',     'CAGCAGTGAGAACTATCTCCGAGA')),
            Adapter('PCR barcoding 80',
                    start_sequence=('BC80_rev', 'CGGATGAACATAGGATAGCGATTC'),
                    end_sequence=  ('BC80',     'GAATCGCTATCCTATGTTCATCCG')),
            Adapter('PCR barcoding 81',
                    start_sequence=('BC81_rev', 'CCTCATCTTGTGAAGTTGTTTCGG'),
                    end_sequence=  ('BC81',     'CCGAAACAACTTCACAAGATGAGG')),
            Adapter('PCR barcoding 82',
                    start_sequence=('BC82_rev', 'ACGGTATGTCGAGTTCCAGGACTA'),
                    end_sequence=  ('BC82',     'TAGTCCTGGAACTCGACATACCGT')),
            Adapter('PCR barcoding 83',
                    start_sequence=('BC83_rev', 'TGGCTTGATCTAGGTAAGGTCGAA'),
                    end_sequence=  ('BC83',     'TTCGACCTTACCTAGATCAAGCCA')),
            Adapter('PCR barcoding 84',
                    start_sequence=('BC84_rev', 'GTAGTGGACCTAGAACCTGTGCCA'),
                    end_sequence=  ('BC84',     'TGGCACAGGTTCTAGGTCCACTAC')),
            Adapter('PCR barcoding 85',
                    start_sequence=('BC85_rev', 'AACGGAGGAGTTAGTTGGATGATC'),
                    end_sequence=  ('BC85',     'GATCATCCAACTAACTCCTCCGTT')),
            Adapter('PCR barcoding 86',
                    start_sequence=('BC86_rev', 'AGGTGATCCCAACAAGCGTAAGTA'),
                    end_sequence=  ('BC86',     'TACTTACGCTTGTTGGGATCACCT')),
            Adapter('PCR barcoding 87',
                    start_sequence=('BC87_rev', 'TACATGCTCCTGTTGTTAGGGAGG'),
                    end_sequence=  ('BC87',     'CCTCCCTAACAACAGGAGCATGTA')),
            Adapter('PCR barcoding 88',
                    start_sequence=('BC88_rev', 'TCTTCTACTACCGATCCGAAGCAG'),
                    end_sequence=  ('BC88',     'CTGCTTCGGATCGGTAGTAGAAGA')),
            Adapter('PCR barcoding 89',
                    start_sequence=('BC89_rev', 'ACAGCATCAATGTTTGGCTAGTTG'),
                    end_sequence=  ('BC89',     'CAACTAGCCAAACATTGATGCTGT')),
            Adapter('PCR barcoding 90',
                    start_sequence=('BC90_rev', 'GATGTAGAGGGTACGGTTTGAGGC'),
                    end_sequence=  ('BC90',     'GCCTCAAACCGTACCCTCTACATC')),
            Adapter('PCR barcoding 91',
                    start_sequence=('BC91_rev', 'GGCTCCATAGGAACTCACGCTACT'),
                    end_sequence=  ('BC91',     'AGTAGCGTGAGTTCCTATGGAGCC')),
            Adapter('PCR barcoding 92',
                    start_sequence=('BC92_rev', 'TTGTGAGTGGAAAGATACAGGACC'),
                    end_sequence=  ('BC92',     'GGTCCTGTATCTTTCCACTCACAA')),
            Adapter('PCR barcoding 93',
                    start_sequence=('BC93_rev', 'AGTTTCCATCACTTCAGACTTGGG'),
                    end_sequence=  ('BC93',     'CCCAAGTCTGAAGTGATGGAAACT')),
            Adapter('PCR barcoding 94',
                    start_sequence=('BC94_rev', 'GATTGTCCTCAAACTGCCACCTAC'),
                    end_sequence=  ('BC94',     'GTAGGTGGCAGTTTGAGGACAATC')),
            Adapter('PCR barcoding 95',
                    start_sequence=('BC95_rev', 'CCTGTCTGGAAGAAGAATGGACTT'),
                    end_sequence=  ('BC95',     'AAGTCCATTCTTCTTCCAGACAGG')),
            Adapter('PCR barcoding 96',
                    start_sequence=('BC96_rev', 'CTGAACGGTCATAGAGTCCACCAT'),
                    end_sequence=  ('BC96',     'ATGGTGGACTCTATGACCGTTCAG'))
            ]
